name: Build and Deploy Angular Project
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Node.js dependencies
        run: npm install
      - name: Install Angular CLI
        run: npm install -g @angular/cli@latest
      - name: Config
        run: ng config -g cli.warnings.versionMismatch false
      - name: Build Angular project
        run: ng build --prod --base-href=/LoginPage/
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist/your-repo-name
